### ISSUE TITLE
Doppeltes Menü

### ISSUE THREAD

**Issue by schorschy** [alexplusde/blaupause#7]
Nachdem man die Blaupause heruntergeladen hat, den Namen des AddOns, der Dateien usw. angepasst hat und das AddOn dann zum ersten Mal installiert, bekommt man im Backend immer ein doppeltes Menü angezeigt.

![ropamanager-·-Wisotel-·-REDAXO-CMS](https://github.com/alexplusde/blaupause/assets/20090597/07c764e8-40ba-4b7f-88d7-cf622cdaa094)

**Comment by alxndr-w** [comment]
Danke für den Hinweis, ursprünglich habe ich den Titel immer global ausgegeben, bei manchen Seiten ist das inzwischen auf "einzeln"
